services:

  server:
    container_name: yaraku-assignment-nginx
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    container_name: yaraku-assignment-laravel
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql:9
    container_name: yaraku-assignment-mysql
    env_file:
      - ./env/mysql.env

  composer:
    container_name: yaraku-assignment-composer
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  npm:
    image: node:20
    container_name: yaraku-assignment-npm
    ports:
      - '5173:5173'
    working_dir: /var/www/html
    command: bash -c "npm install && npm run dev -- --host"
    volumes:
      - ./src:/var/www/html