---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: src/vendor
          key: composer-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Copy .env file
        working-directory: ./src
        run: |
          cp .env.ci .env
      
      - name: Generate Application Key
        working-directory: ./src
        run: |
          php artisan key:generate
      
      - name: Run composer
        working-directory: ./src
        run: |
          composer install --no-interaction

      - name: Run test suite
        working-directory: ./src
        run: |
          php artisan test
      
      - name: Run linting
        working-directory: ./src
        run: |
          ./vendor/bin/pint --test -v